# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_apps', '0003_quote_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorited',
        ),
    ]
